export const BOOKS_DATA = [
  { amharic: "ኦሪት ዘፍጥረት", english: "Genesis", abbr: "ዘፍ", abbrEnglish: "Gen", chapters: 50 },
  { amharic: "ኦሪት ዘጸአት", english: "Exodus", abbr: "ዘጸ", abbrEnglish: "Exod", chapters: 40 },
  { amharic: "ኦሪት ዘሌዋውያን", english: "Leviticus", abbr: "ዘሌ", abbrEnglish: "Lev", chapters: 27 },
  { amharic: "ኦሪት ዘኍልቍ", english: "Numbers", abbr: "ዘኍ", abbrEnglish: "Num", chapters: 36 },
  { amharic: "ኦሪት ዘዳግም", english: "Deuteronomy", abbr: "ዘዳ", abbrEnglish: "Deut", chapters: 34 },
  { amharic: "መጽሐፈ ኢያሱ ወልደ ነዌ", english: "Joshua", abbr: "ኢያ", abbrEnglish: "Josh", chapters: 24 },
  { amharic: "መጽሐፈ መሣፍንት", english: "Judges", abbr: "መሳ", abbrEnglish: "Judg", chapters: 21 },
  { amharic: "መጽሐፈ ሩት", english: "Ruth", abbr: "ሩት", abbrEnglish: "Ruth", chapters: 4 },
  {
    amharic: "መጽሐፈ ሳሙኤል ቀዳማዊ",
    english: "1 Samuel",
    abbr: "1 ሳሙ",
    abbrEnglish: "1 Sam",
    chapters: 31,
  },
  { amharic: "መጽሐፈ ሳሙኤል ካል", english: "2 Samuel", abbr: "2 ሳሙ", abbrEnglish: "2 Sam", chapters: 24 },
  { amharic: "መጽሐፈ ነገሥት ቀዳማዊ", english: "1 Kings", abbr: "1 ነገ", abbrEnglish: "1 Kgs", chapters: 22 },
  { amharic: "መጽሐፈ ነገሥት ካልዕ", english: "2 Kings", abbr: "2 ነገ", abbrEnglish: "2 Kgs", chapters: 25 },
  {
    amharic: "መጽሐፈ ዜና መዋዕል ቀዳማዊ",
    english: "1 Chronicles",
    abbr: "1 ዜና",
    abbrEnglish: "1 Chr",
    chapters: 29,
  },
  {
    amharic: "መጽሐፈ ዜና መዋዕል ካልዕ",
    english: "2 Chronicles",
    abbr: "2 ዜና",
    abbrEnglish: "2 Chr",
    chapters: 36,
  },
  { amharic: "መጽሐፈ ዕዝራ", english: "Ezra", abbr: "ዕዝ", abbrEnglish: "Ezra", chapters: 10 },
  { amharic: "መጽሐፈ ነህምያ", english: "Nehemiah", abbr: "ነህ", abbrEnglish: "Neh", chapters: 13 },
  { amharic: "መጽሐፈ አስቴር", english: "Esther", abbr: "አስ", abbrEnglish: "Esth", chapters: 10 },
  { amharic: "መጽሐፈ ኢዮብ", english: "Job", abbr: "ኢዮ", abbrEnglish: "Job", chapters: 42 },
  { amharic: "መዝሙረ ዳዊት", english: "Psalms", abbr: "መዝ", abbrEnglish: "Ps", chapters: 150 },
  { amharic: "መጽሐፈ ምሳሌ", english: "Proverbs", abbr: "ምሳ", abbrEnglish: "Prov", chapters: 31 },
  { amharic: "መጽሐፈ መክብብ", english: "Ecclesiastes", abbr: "መክ", abbrEnglish: "Eccl", chapters: 12 },
  {
    amharic: "መኃልየ መኃልይ ዘሰሎሞን",
    english: "Song of Songs",
    abbr: "መሃ",
    abbrEnglish: "Song",
    chapters: 8,
  },
  { amharic: "ትንቢተ ኢሳይያስ", english: "Isaiah", abbr: "ኢሳ", abbrEnglish: "Isa", chapters: 66 },
  { amharic: "ትንቢተ ኤርምያስ", english: "Jeremiah", abbr: "ኤር", abbrEnglish: "Jer", chapters: 52 },
  { amharic: "ሰቆቃው ኤርምያስ", english: "Lamentations", abbr: "ሰቆ", abbrEnglish: "Lam", chapters: 5 },
  { amharic: "ትንቢተ ሕዝቅኤል", english: "Ezekiel", abbr: "ሕዝ", abbrEnglish: "Ezek", chapters: 48 },
  { amharic: "ትንቢተ ዳንኤል", english: "Daniel", abbr: "ዳን", abbrEnglish: "Dan", chapters: 12 },
  { amharic: "ትንቢተ ሆሴዕ", english: "Hosea", abbr: "ሆሴ", abbrEnglish: "Hos", chapters: 14 },
  { amharic: "ትንቢተ ኢዮኤል", english: "Joel", abbr: "ኢዮኤ", abbrEnglish: "Joel", chapters: 3 },
  { amharic: "ትንቢተ አሞጽ", english: "Amos", abbr: "አሞ", abbrEnglish: "Amos", chapters: 9 },
  { amharic: "ትንቢተ አብድዩ", english: "Obadiah", abbr: "አብ", abbrEnglish: "Obad", chapters: 1 },
  { amharic: "ትንቢተ ዮናስ", english: "Jonah", abbr: "ዮና", abbrEnglish: "Jonah", chapters: 4 },
  { amharic: "ትንቢተ ሚክያስ", english: "Micah", abbr: "ሚክ", abbrEnglish: "Mic", chapters: 7 },
  { amharic: "ትንቢተ ናሆም", english: "Nahum", abbr: "ናሆ", abbrEnglish: "Nah", chapters: 3 },
  { amharic: "ትንቢተ ዕንባቆም", english: "Habakkuk", abbr: "ዕብ", abbrEnglish: "Hab", chapters: 3 },
  { amharic: "ትንቢተ ሶፎንያስ", english: "Zephaniah", abbr: "ሶፎ", abbrEnglish: "Zeph", chapters: 3 },
  { amharic: "ትንቢተ ሐጌ", english: "Haggai", abbr: "ሐጌ", abbrEnglish: "Hag", chapters: 2 },
  { amharic: "ትንቢተ ዘካርያስ", english: "Zechariah", abbr: "ዘካ", abbrEnglish: "Zech", chapters: 14 },
  { amharic: "ትንቢተ ሚልክያ", english: "Malachi", abbr: "ሚል", abbrEnglish: "Mal", chapters: 4 },
  { amharic: "የማቴዎስ ወንጌል", english: "Matthew", abbr: "ማቴ", abbrEnglish: "Matt", chapters: 28 },
  { amharic: "የማርቆስ ወንጌል", english: "Mark", abbr: "ማር", abbrEnglish: "Mark", chapters: 16 },
  { amharic: "የሉቃስ ወንጌል", english: "Luke", abbr: "ሉቃ", abbrEnglish: "Luke", chapters: 24 },
  { amharic: "የዮሐንስ ወንጌል", english: "John", abbr: "ዮሐ", abbrEnglish: "John", chapters: 21 },
  { amharic: "የሐዋርያት ሥራ", english: "Acts", abbr: "ሐዋ", abbrEnglish: "Acts", chapters: 28 },
  { amharic: "ወደ ሮሜ ሰዎች", english: "Romans", abbr: "ሮሜ", abbrEnglish: "Rom", chapters: 16 },
  {
    amharic: "1ኛ ወደ ቆሮንቶስ ሰዎች",
    english: "1 Corinthians",
    abbr: "1 ቆሮ",
    abbrEnglish: "1 Cor",
    chapters: 16,
  },
  {
    amharic: "2ኛ ወደ ቆሮንቶስ ሰዎች",
    english: "2 Corinthians",
    abbr: "2 ቆሮ",
    abbrEnglish: "2 Cor",
    chapters: 13,
  },
  { amharic: "ወደ ገላትያ ሰዎች", english: "Galatians", abbr: "ገላ", abbrEnglish: "Gal", chapters: 6 },
  { amharic: "ወደ ኤፌሶን ሰዎች", english: "Ephesians", abbr: "ኤፌ", abbrEnglish: "Eph", chapters: 6 },
  { amharic: "ወደ ፊልጵስዩስ ሰዎች", english: "Philippians", abbr: "ፊል", abbrEnglish: "Phil", chapters: 4 },
  { amharic: "ወደ ቆላስይስ ሰዎች", english: "Colossians", abbr: "ቆላ", abbrEnglish: "Col", chapters: 4 },
  {
    amharic: "1ኛ ወደ ተሰሎንቄ ሰዎች",
    english: "1 Thessalonians",
    abbr: "1 ተሰ",
    abbrEnglish: "1 Thess",
    chapters: 5,
  },
  {
    amharic: "2ኛ ወደ ተሰሎንቄ ሰዎች",
    english: "2 Thessalonians",
    abbr: "2 ተሰ",
    abbrEnglish: "2 Thess",
    chapters: 3,
  },
  { amharic: "1ኛ ወደ ጢሞቴዎስ", english: "1 Timothy", abbr: "1 ጢሞ", abbrEnglish: "1 Tim", chapters: 6 },
  { amharic: "2ኛ ወደ ጢሞቴዎስ", english: "2 Timothy", abbr: "2 ጢሞ", abbrEnglish: "2 Tim", chapters: 4 },
  { amharic: "ወደ ቲቶ", english: "Titus", abbr: "ቲቶ", abbrEnglish: "Titus", chapters: 3 },
  { amharic: "ወደ ፊልሞና", english: "Philemon", abbr: "ፊልሞ", abbrEnglish: "Phlm", chapters: 1 },
  { amharic: "ወደ ዕብራውያን", english: "Hebrews", abbr: "ዕብ", abbrEnglish: "Heb", chapters: 13 },
  { amharic: "የያዕቆብ መልእክት", english: "James", abbr: "ያዕ", abbrEnglish: "Jas", chapters: 5 },
  { amharic: "1ኛ የጴጥሮስ መልእክት", english: "1 Peter", abbr: "1 ጴጥ", abbrEnglish: "1 Pet", chapters: 5 },
  { amharic: "2ኛ የጴጥሮስ መልእክት", english: "2 Peter", abbr: "2 ጴጥ", abbrEnglish: "2 Pet", chapters: 3 },
  { amharic: "1ኛ የዮሐንስ መልእክት", english: "1 John", abbr: "1 ዮሐ", abbrEnglish: "1 John", chapters: 5 },
  { amharic: "2ኛ የዮሐንስ መልእክት", english: "2 John", abbr: "2 ዮሐ", abbrEnglish: "2 John", chapters: 1 },
  { amharic: "3ኛ የዮሐንስ መልእክት", english: "3 John", abbr: "3 ዮሐ", abbrEnglish: "3 John", chapters: 1 },
  { amharic: "የይሁዳ መልእክት", english: "Jude", abbr: "ይሁ", abbrEnglish: "Jude", chapters: 1 },
  { amharic: "የዮሐንስ ራእይ", english: "Revelation", abbr: "ራእ", abbrEnglish: "Rev", chapters: 22 },
];

export const amharicBooks = BOOKS_DATA.map((book) => ({
  name: book.english,
  amharic: book.amharic,
  abbr: book.abbr,
  abbrEnglish: book.abbrEnglish,
  chapters: book.chapters,
}));
