export const BOOKS_DATA = [
  { amharic: "ኦሪት ዘፍጥረት", english: "Genesis", abbr: "ዘፍ", chapters: 50 },
  { amharic: "ኦሪት ዘጸአት", english: "Exodus", abbr: "ዘጸ", chapters: 40 },
  { amharic: "ኦሪት ዘሌዋውያን", english: "Leviticus", abbr: "ዘሌ", chapters: 27 },
  { amharic: "ኦሪት ዘኍልቍ", english: "Numbers", abbr: "ዘኍ", chapters: 36 },
  { amharic: "ኦሪት ዘዳግም", english: "Deuteronomy", abbr: "ዘዳ", chapters: 34 },
  { amharic: "መጽሐፈ ኢያሱ ወልደ ነዌ", english: "Joshua", abbr: "ኢያ", chapters: 24 },
  { amharic: "መጽሐፈ መሣፍንት", english: "Judges", abbr: "መሳ", chapters: 21 },
  { amharic: "መጽሐፈ ሩት", english: "Ruth", abbr: "ሩት", chapters: 4 },
  {
    amharic: "መጽሐፈ ሳሙኤል ቀዳማዊ",
    english: "1 Samuel",
    abbr: "1 ሳሙ",
    chapters: 31,
  },
  { amharic: "መጽሐፈ ሳሙኤል ካል", english: "2 Samuel", abbr: "2 ሳሙ", chapters: 24 },
  { amharic: "መጽሐፈ ነገሥት ቀዳማዊ", english: "1 Kings", abbr: "1 ነገ", chapters: 22 },
  { amharic: "መጽሐፈ ነገሥት ካልዕ", english: "2 Kings", abbr: "2 ነገ", chapters: 25 },
  {
    amharic: "መጽሐፈ ዜና መዋዕል ቀዳማዊ",
    english: "1 Chronicles",
    abbr: "1 ዜና",
    chapters: 29,
  },
  {
    amharic: "መጽሐፈ ዜና መዋዕል ካልዕ",
    english: "2 Chronicles",
    abbr: "2 ዜና",
    chapters: 36,
  },
  { amharic: "መጽሐፈ ዕዝራ", english: "Ezra", abbr: "ዕዝ", chapters: 10 },
  { amharic: "መጽሐፈ ነህምያ", english: "Nehemiah", abbr: "ነህ", chapters: 13 },
  { amharic: "መጽሐፈ አስቴር", english: "Esther", abbr: "አስ", chapters: 10 },
  { amharic: "መጽሐፈ ኢዮብ", english: "Job", abbr: "ኢዮ", chapters: 42 },
  { amharic: "መዝሙረ ዳዊት", english: "Psalms", abbr: "መዝ", chapters: 150 },
  { amharic: "መጽሐፈ ምሳሌ", english: "Proverbs", abbr: "ምሳ", chapters: 31 },
  { amharic: "መጽሐፈ መክብብ", english: "Ecclesiastes", abbr: "መክ", chapters: 12 },
  {
    amharic: "መኃልየ መኃልይ ዘሰሎሞን",
    english: "Song of Songs",
    abbr: "መሃ",
    chapters: 8,
  },
  { amharic: "ትንቢተ ኢሳይያስ", english: "Isaiah", abbr: "ኢሳ", chapters: 66 },
  { amharic: "ትንቢተ ኤርምያስ", english: "Jeremiah", abbr: "ኤር", chapters: 52 },
  { amharic: "ሰቆቃው ኤርምያስ", english: "Lamentations", abbr: "ሰቆ", chapters: 5 },
  { amharic: "ትንቢተ ሕዝቅኤል", english: "Ezekiel", abbr: "ሕዝ", chapters: 48 },
  { amharic: "ትንቢተ ዳንኤል", english: "Daniel", abbr: "ዳን", chapters: 12 },
  { amharic: "ትንቢተ ሆሴዕ", english: "Hosea", abbr: "ሆሴ", chapters: 14 },
  { amharic: "ትንቢተ ኢዮኤል", english: "Joel", abbr: "ኢዮኤ", chapters: 3 },
  { amharic: "ትንቢተ አሞጽ", english: "Amos", abbr: "አሞ", chapters: 9 },
  { amharic: "ትንቢተ አብድዩ", english: "Obadiah", abbr: "አብ", chapters: 1 },
  { amharic: "ትንቢተ ዮናስ", english: "Jonah", abbr: "ዮና", chapters: 4 },
  { amharic: "ትንቢተ ሚክያስ", english: "Micah", abbr: "ሚክ", chapters: 7 },
  { amharic: "ትንቢተ ናሆም", english: "Nahum", abbr: "ናሆ", chapters: 3 },
  { amharic: "ትንቢተ ዕንባቆም", english: "Habakkuk", abbr: "ዕብ", chapters: 3 },
  { amharic: "ትንቢተ ሶፎንያስ", english: "Zephaniah", abbr: "ሶፎ", chapters: 3 },
  { amharic: "ትንቢተ ሐጌ", english: "Haggai", abbr: "ሐጌ", chapters: 2 },
  { amharic: "ትንቢተ ዘካርያስ", english: "Zechariah", abbr: "ዘካ", chapters: 14 },
  { amharic: "ትንቢተ ሚልክያ", english: "Malachi", abbr: "ሚል", chapters: 4 },
  { amharic: "የማቴዎስ ወንጌል", english: "Matthew", abbr: "ማቴ", chapters: 28 },
  { amharic: "የማርቆስ ወንጌል", english: "Mark", abbr: "ማር", chapters: 16 },
  { amharic: "የሉቃስ ወንጌል", english: "Luke", abbr: "ሉቃ", chapters: 24 },
  { amharic: "የዮሐንስ ወንጌል", english: "John", abbr: "ዮሐ", chapters: 21 },
  { amharic: "የሐዋርያት ሥራ", english: "Acts", abbr: "ሐዋ", chapters: 28 },
  { amharic: "ወደ ሮሜ ሰዎች", english: "Romans", abbr: "ሮሜ", chapters: 16 },
  {
    amharic: "1ኛ ወደ ቆሮንቶስ ሰዎች",
    english: "1 Corinthians",
    abbr: "1 ቆሮ",
    chapters: 16,
  },
  {
    amharic: "2ኛ ወደ ቆሮንቶስ ሰዎች",
    english: "2 Corinthians",
    abbr: "2 ቆሮ",
    chapters: 13,
  },
  { amharic: "ወደ ገላትያ ሰዎች", english: "Galatians", abbr: "ገላ", chapters: 6 },
  { amharic: "ወደ ኤፌሶን ሰዎች", english: "Ephesians", abbr: "ኤፌ", chapters: 6 },
  { amharic: "ወደ ፊልጵስዩስ ሰዎች", english: "Philippians", abbr: "ፊል", chapters: 4 },
  { amharic: "ወደ ቆላስይስ ሰዎች", english: "Colossians", abbr: "ቆላ", chapters: 4 },
  {
    amharic: "1ኛ ወደ ተሰሎንቄ ሰዎች",
    english: "1 Thessalonians",
    abbr: "1 ተሰ",
    chapters: 5,
  },
  {
    amharic: "2ኛ ወደ ተሰሎንቄ ሰዎች",
    english: "2 Thessalonians",
    abbr: "2 ተሰ",
    chapters: 3,
  },
  { amharic: "1ኛ ወደ ጢሞቴዎስ", english: "1 Timothy", abbr: "1 ጢሞ", chapters: 6 },
  { amharic: "2ኛ ወደ ጢሞቴዎስ", english: "2 Timothy", abbr: "2 ጢሞ", chapters: 4 },
  { amharic: "ወደ ቲቶ", english: "Titus", abbr: "ቲቶ", chapters: 3 },
  { amharic: "ወደ ፊልሞና", english: "Philemon", abbr: "ፊልሞ", chapters: 1 },
  { amharic: "ወደ ዕብራውያን", english: "Hebrews", abbr: "ዕብ", chapters: 13 },
  { amharic: "የያዕቆብ መልእክት", english: "James", abbr: "ያዕ", chapters: 5 },
  { amharic: "1ኛ የጴጥሮስ መልእክት", english: "1 Peter", abbr: "1 ጴጥ", chapters: 5 },
  { amharic: "2ኛ የጴጥሮስ መልእክት", english: "2 Peter", abbr: "2 ጴጥ", chapters: 3 },
  { amharic: "1ኛ የዮሐንስ መልእክት", english: "1 John", abbr: "1 ዮሐ", chapters: 5 },
  { amharic: "2ኛ የዮሐንስ መልእክት", english: "2 John", abbr: "2 ዮሐ", chapters: 1 },
  { amharic: "3ኛ የዮሐንስ መልእክት", english: "3 John", abbr: "3 ዮሐ", chapters: 1 },
  { amharic: "የይሁዳ መልእክት", english: "Jude", abbr: "ይሁ", chapters: 1 },
  { amharic: "የዮሐንስ ራእይ", english: "Revelation", abbr: "ራእ", chapters: 22 },
];

export const amharicBooks = BOOKS_DATA.map((book) => ({
  name: book.english,
  amharic: book.amharic,
  abbr: book.abbr,
  chapters: book.chapters,
}));
